### ISSUE TITLE
Use offset instead of limit

### ISSUE THREAD

**Issue by sergeivolodin** [tournesol-app/tournesol-twitter-bot#7]
https://github.com/tournesol-app/tournesol-twitter-bot/blob/b204b3acd62fdafb9fde78ff0bd6faee05aed238/tournesolbot/tournesol_api_functions.py#L37

To load the second page of results, you can use the `offset` query parameter.

The results are always [offset, offset+limit]

**Comment by aidanjungo** [comment]
What to you mean by "second page"?
I am not sure I understand how I should use it with offset to get the top 50 best videos.
